YourArea/urls.py
from django.urls import path, include, re_path
from .views import *
import django.conf.urls

app_name = "YourArea"

urlpatterns = [
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    path("", dashboard, name="dashboard"),
    path("area_list/", profile_list, name="profile_list"),
    path("area/<int:pk>", profile, name="profile"),
    path("area/followers/<int:pk>", followers, name="followers"),
    path("area/following/<int:pk>", following, name="following"),
    path("post/<int:pk>", post, name="post"),
    path("post/<int:post_pk>/comment/<int:pk>/reply", CommentReplyView.as_view(), name="comment_reply"),
    path("post/likes/<int:pk>", likes, name="likes"),
    path("update_area/", update_area, name="update_area"),
    path("post_like/<int:pk>", post_like, name="post_like"),
    path("comment_like/<int:post_pk>/comment/<int:pk>/like", comment_like, name="comment_like"),
    path("delete_post/<int:pk>", delete_post, name="delete_post"),
    path("search/", search, name="search"),
    path('notification/<int:notification_pk>/post/<int:post_pk>', PostNotification.as_view(), name="post_notification"),
    path('notification/<int:notification_pk>/profile/<int:profile_pk>', FollowNotification.as_view(), name="follow_notification"),
    path('notification/delete/<int:notification_pk>', RemoveNotification.as_view(), name="notification_delete"),
    re_path(r"^register/", register, name="register"),
]

social/social/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('yourarea.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yourarea/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('@<str:username>', views.profile, name='area'),
    path('area/followers/<int:pk>/', views.followers, name='followers'),
    path('area/following/<int:pk>/', views.following, name='following'),
    path('update_area/', views.update_profile, name='update_area'),
    path('like-post/<int:post_id>/', views.like_post, name='like_post'),
    path('dislike-post/<int:post_id>/', views.dislike_post, name='dislike_post'),
    path('post/<int:pk>/', views.post, name='post'),
    path('delete-post/<int:pk>/', views.delete_post, name='delete_post'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications/mark-as-read/<int:notification_id>', views.mark_as_read, name='mark_as_read'),
    path("notifications/delete/<int:notification_id>/", views.delete_notification, name="delete_notification"),
    path('groups/', views.groups_list, name='groups_list'),
    path('group/create', views.create_group, name='create_group'),
    path('group/<slug:slug>', views.group, name='group'),
    path('group/<slug:slug>/join', views.join_group, name='join_group'),
    path('group/<slug:slug>/leave', views.leave_group, name='leave_group'),
    path('group/<slug:slug>/update', views.update_group, name='update_group'),
    path('group/<slug:slug>/create-event', views.create_event, name='create_event'),
    path('search/', views.search, name='search'),
    path('areas/', views.profiles_list, name='areas_list'),
]

YourArea/forms.py
from django import forms
from .models import Post, Comment, Profile
from django.contrib.auth.forms import UserCreationForm

class PostForm(forms.ModelForm):
    body = forms.CharField(
        required=False,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Post something...",
                "class": "textarea is-medium",
            }
        ),
        label="",
    )

    post_image = forms.ImageField(required=False)

    def clean(self):
        cleaned_data = super().clean()
        body = cleaned_data.get('body')
        post_image = cleaned_data.get('post_image')

        if not body and not post_image:
            raise forms.ValidationError(
                "You must fill in at least one of the fields."
            )

        return cleaned_data


    class Meta:
        model = Post
        exclude = ("user", "likes", )

class CommentForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Comment something...",
                "class": "textarea is-success is-medium",
            }
        ),
        label="",
    )
    

    class Meta:
        model = Comment
        exclude = ("user", "post", "likes", "parent")

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)

    def clean_username(self):
        username = self.cleaned_data.get('username')  # get the username data
        lowercase_username = username.lower()         # get the lowercase version of it

        return lowercase_username
        


class ProfileExtrasForm(forms.ModelForm):
    display_name = forms.CharField(label="Area name", widget=forms.widgets.Textarea(attrs={"class": "input"}))
    profile_image = forms.ImageField(label="Area picture")
    profile_bio = forms.CharField(label="Bio", required=False, widget=forms.widgets.Textarea(attrs={"placeholder": "Describe yourself...","class": "textarea",}))

    background_image = forms.ImageField(label="Background image", required=False)

    favourite_colour = forms.CharField(widget=forms.TextInput(attrs={"type": 'color'}))

    spotify_id = forms.CharField(label="Spotify song ID", required=False, widget=forms.TextInput(attrs={"class": "input"}))

    youtube_link = forms.CharField(label="YouTube", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    twitch_link = forms.CharField(label="Twitch", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    tiktok_link = forms.CharField(label="TikTok", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    instagram_link = forms.CharField(label="Instagram", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    custom_link = forms.CharField(label="Add site", required=False, widget=forms.TextInput(attrs={"class": "input"}))

    general_interests = forms.CharField(label="General interests", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    music_interests = forms.CharField(label="Music interests", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    television_interests = forms.CharField(label="Television interests", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    movies_interests = forms.CharField(label="Movies interests", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    books_interests = forms.CharField(label="Books interests", required=False, widget=forms.TextInput(attrs={"class": "input"}))

    class Meta:
        model = Profile
        fields = ('display_name', 'profile_image', 'profile_bio', 'background_image', 'favourite_colour', 'spotify_id', 'youtube_link', 'twitch_link', 'tiktok_link', 'instagram_link', 'custom_link', 'general_interests', 'music_interests', 'television_interests', 'movies_interests', 'books_interests',)

YourArea/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from .models import *
from django.contrib.auth import login
from django.urls import reverse
from django.views import View
from django.http import HttpResponse

def dashboard(request):
    if request.user.is_authenticated:
        user_profile = Profile.objects.get(user__id=request.user.id)
        followed_posts = Post.objects.filter(user__id__in=request.user.profile.follows.all().values_list('user_id')).order_by("-created_at")
    else:
        followed_posts = None
    all_posts = Post.objects.all().order_by("-created_at")

    return render(
        request,
        "YourArea/dashboard.html",
        {"posts": all_posts, "followed_posts": followed_posts},
    )

def profile_list(request):
    profiles = Profile.objects.all().order_by("-date_modified")
    return render(request, "YourArea/profile_list.html", {"profiles": profiles})

def profile(request, pk):
    profile = Profile.objects.get(pk=pk)
    posts = profile.user.posts.all().order_by("-created_at")

    if request.user.is_authenticated:
        if not hasattr(request.user, 'profile'):
            missing_profile = profile(user=request.user)
            missing_profile.save()

        if request.method == "POST":
            current_user_profile = request.user.profile
            data = request.POST
            action = data.get("follow")
            if action == "follow":
                current_user_profile.follows.add(profile)
                notification = Notification.objects.create(notification_type=3, from_user=request.user, to_user=profile.user)
            elif action == "unfollow":
                current_user_profile.follows.remove(profile)
            current_user_profile.save()

            form = PostForm(request.POST or None, request.FILES or None)
            if form.is_valid():
                post = form.save(commit=False)
                post.user = request.user
                post.save()
                return redirect("YourArea:profile", current_user_profile.id)
        
    return render(request, "YourArea/profile.html", {"form": PostForm(), "profile": profile, "posts": posts})

def followers(request, pk):
    profiles = Profile.objects.get(user_id=pk)
    return render(request, "YourArea/followers.html", {"profiles": profiles})

def following(request, pk):
    profiles = Profile.objects.get(user_id=pk)
    return render(request, "YourArea/following.html", {"profiles": profiles})

def likes(request, pk):
    post = Post.objects.get(id=pk)
    users = post.likes.all()

    return render(request, "YourArea/likes.html", {"profiles": users})

def update_area(request):
    if request.user.is_authenticated:
        current_user = User.objects.get(id=request.user.id)
        profile_user = Profile.objects.get(user__id=request.user.id)

        # user_form = CustomUserCreationForm(request.POST or None, request.FILES or None, instance=current_user)
        profile_form = ProfileExtrasForm(request.POST or None, request.FILES or None, instance=profile_user, use_required_attribute=False)
        if profile_form.is_valid():
            # user_form.save()
            profile_form.save()
            # login(request, current_user)
            print("user changed")
            return redirect('YourArea:profile', current_user.profile.id)
        print("user not changed")
        return render(request, "YourArea/update_area.html", {'form': profile_form})
    else:
        return redirect('YourArea:dashboard')

def post(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST or None)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            notification = Notification.objects.create(notification_type=2, from_user=request.user, to_user=post.user, post=post)

    form = CommentForm()

    comments = Comment.objects.filter(post=post).order_by("-created_at")

    return render(
        request,
        "YourArea/post.html",
        {"form": form, "post": post, "comments": comments},
    )

class CommentReplyView(View):
    def post(self, request, post_pk, pk, *args, **kwargs):
        post = Post.objects.get(pk=post_pk)
        parent_comment = Comment.objects.get(pk=pk)
        form = CommentForm(request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post
            new_comment.parent = parent_comment
            new_comment.save()

        return redirect('YourArea:post', pk=post_pk)

def register(request):
    if request.method == "GET":
        return render(
            request, "YourArea/register.html",
            {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.backend = "django.contrib.auth.backends.ModelBackend"
            user.save()
            login(request, user)
            return redirect(reverse("YourArea:dashboard"))
        else:
            return render(
                request, "YourArea/register.html",
                {"form": CustomUserCreationForm}
            )

def post_like(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, id=pk)
        if post.likes.filter(id=request.user.id):
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)
            notification = Notification.objects.create(notification_type=1, from_user=request.user, to_user=post.user, post=post)
        return redirect(request.META.get("HTTP_REFERER"))

    else:
        return redirect('YourArea:login')

def comment_like(request, pk, *args, **kwargs):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, id=pk)
        if comment.likes.filter(id=request.user.id):
            comment.likes.remove(request.user)
        else:
            comment.likes.add(request.user)
            # notification = Notification.objects.create(notification_type=1, from_user=request.user, to_user=comment.user, post=post)
        return redirect(request.META.get("HTTP_REFERER"))

    else:
        return redirect('YourArea:login')

def delete_post(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, id=pk)
        if request.user.username == post.user.username:
            post.delete()
        return redirect(request.META.get("HTTP_REFERER"))

    else:
        return redirect(request.META.get("HTTP_REFERER"))

def search(request):
    if request.method == "POST":
        search = request.POST['search']

        searched = Post.objects.filter(body__contains = search).order_by("-created_at")
        searched_profiles = Profile.objects.filter(user__username__contains = search)

        return render(request, 'YourArea/search.html', {'search': search, 'searched': searched, 'searched_profiles': searched_profiles})
    else:
        return render(request, 'YourArea/search.html', {})

class PostNotification(View):
    def get(self, request, notification_pk, post_pk, *args, **kwargs):
        notification = Notification.objects.get(pk=notification_pk)
        post = Post.objects.get(pk=post_pk)

        notification.user_has_seen = True
        notification.save()

        return redirect('YourArea:post', pk=post_pk)

class FollowNotification(View):
    def get(self, request, notification_pk, profile_pk, *args, **kwargs):
        notification = Notification.objects.get(pk=notification_pk)
        profile = Profile.objects.get(pk=profile_pk)

        notification.user_has_seen = True
        notification.save()

        return redirect('YourArea:profile', pk=profile_pk)

class RemoveNotification(View):
    def delete(self, request, notification_pk, *args, **kwargs):
        notification = Notification.objects.get(pk=notification_pk)

        notification.user_has_seen = True
        notification.save()
        return HttpResponse('Success', content_type='text/plain')

YourArea/templates/YourArea/tags/show_area_list_profile.html
<style>
    .box {
      width: 20rem;
      height: 20rem;
      padding: 5px;
    }

    @media (max-width: 768px) {
        .box {
            width: 100%;
            margin: 1rem 0rem;
        }
    }

    .profile_block {
        background-color: white;
        width: 100%;
        height: 100%;
        padding: 5px;
        border-radius: 3px;
        border-color: black;
    }
    
  </style>
      <script>console.log("{{profiles}}")</script>
  <div class="columns is-multiline is-centered">
  {% for profile in profiles %}
        <style>
            .outline-{{profile.id}} {
                background-color: {{profile.favourite_colour}};
                }
        </style>

        <script>console.log("{{profile.favourite_colour}}")</script>
  
        <div class="column is-3">
          <a href="{% url 'YourArea:profile' profile.id %}">
            <div class="box outline-{{profile.id}}">
              <div class="block profile_block">
                <div class="columns is-gapless">
                  <div class="column">
                    <figure class="image is-128x128">
                      {% if profile.profile_image %}
                        <img src="{{ profile.profile_image.url }}" alt="">
                      {% else %}
                      <img src="https://bulma.io/assets/images/placeholders/256x256.png"
                           alt="Placeholder image">
                      {% endif %}
                      </figure>
                  </div>
                  <div class="column">
                    <p class="title is-4">
                      {% if profile.display_name %}
                        {{ profile.display_name }}
                      {% else %}
                        {{ profile.user.username }}
                      {% endif %}
                    </p>
                    <p class="subtitle is-6">
                      @{{ profile.user.username }}
                    </p>
                  </div>
                </div>
  
                {% if profile.profile_bio %}
                  <p>
                    {{ profile.profile_bio }}
                  </p>
                {% endif %}
                  
              </div>
            </div>
          </a>
        </div>
  
  {% endfor %}
  <div class="column"></div>
  </div>

YourArea/templates/YourArea/tags/show_notifications.html
<div class="dropdown">
    <div class="dropdown-trigger">
        <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
          <span>{{ notifications.count }} notifications</span>
          <span class="icon is-small">
            <i class="fas fa-angle-down" aria-hidden="true"></i>
          </span>
        </button>
      </div>
      <div class="dropdown-menu" id="dropdown-menu" role="menu">
        <div class="dropdown-content">
            {% for notification in notifications %}
            {% if notification.post %}
                {% if notification.notification_type == 1 %}
                    <div class="notification has-text-dark">
                        <a href="{% url 'YourArea:post_notification' notification.pk notification.post.pk %}">@{{ notification.from_user }} liked your post</a>
                        <button class="delete" onclick="removeNotification(`{% url 'YourArea:notification_delete' notification.pk %}`, `{{ request.path }}`)"></button>
                    </div>
                {% elif notification.notification_type == 2 %}
                    <div class="notification has-text-dark">
                        <a href="{% url 'YourArea:post_notification' notification.pk notification.post.pk %}">@{{ notification.from_user }} commented on your post</a>
                        <button class="delete" onclick="removeNotification(`{% url 'YourArea:notification_delete' notification.pk %}`, `{{ request.path }}`)"></button>
                    </div>
                {% endif %}
            <!-- ctrl-z me -->
            {% else %}
                <div class="notification has-text-dark">
                    <a href="{% url 'YourArea:follow_notification' notification.pk notification.from_user.profile.pk %}">@{{ notification.from_user }} followed you</a>
                    <button class="delete" onclick="removeNotification(`{% url 'YourArea:notification_delete' notification.pk %}`, `{{ request.path }}`)"></button>
                </div>
            {% endif %}
        {% endfor %}
        </div>
    </div>
</div>

<script>
    const dropdown = document.querySelector('.dropdown');
    const dropdown_trigger = document.querySelector('.dropdown-trigger');
    dropdown_trigger.addEventListener('click', () => {
            dropdown.classList.toggle('is-active')
        })

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                }
            }
        }
        return cookieValue;
    }

    function removeNotification(removeNotificationURL, redirectURL) {
        const csrftoken = getCookie('csrftoken');
        let xmlhttp = new XMLHttpRequest();

        xmlhttp.onreadystatechange = function() {
            if (xmlhttp.readyState == XMLHttpRequest.DONE) {
                if (xmlhttp.status == 200) {
                    window.location.replace(redirectURL);
                } else {
                    alert('There was an error');
                }
            }
        };

        xmlhttp.open("DELETE", removeNotificationURL, true);
        xmlhttp.setRequestHeader("X-CSRFToken", csrftoken);
        xmlhttp.send();
    }
</script>

YourArea/templates/YourArea/tags/show_posts.html
{% for post in posts %}
    <style>
        .post-image {
            border-radius: 2rem;
        }
    </style>

    <div class="block">
        <a href="{% url 'YourArea:post' post.id %}">
            <div class="media">
                <div class="media-left">
                    <a href="{% url 'YourArea:profile' post.user.profile.id %}">
                        <p class="image is-48x48">
                            {% if post.user.profile.profile_image %}
                                <img class="is-rounded" src="{{ post.user.profile.profile_image.url }}">
                            {% else %}
                                <img class="is-rounded" src="https://bulma.io/assets/images/placeholders/128x128.png" />
                            {% endif %}
                        </p>
                    </a>
                </div>
                <div class="media-content is-fullwidth">
                    {% if post.user.profile.display_name %}
                    <p class="mb-0"><strong class="has-text-dark">{{ post.user.profile.display_name }}</strong> <small class="has-text-grey">@{{ post.user.username }}</small></p>
                    {% else %}
                    <p class="mb-0"><strong class="has-text-dark">{{ post.user.username }}</strong> <small class="has-text-grey">@{{ post.user.username }}</small></p>
                    {% endif %}
                    <a href="{% url 'YourArea:post' post.id %}">
                        <p class="is-text has-text-grey-dark">{{post.body}}</p>
                        {% if post.post_image %}
                            <img class="post-image" src="{{ post.post_image.url }}" alt="">
                        {% endif %}
                    </a>
                    <p>
                        {% if user in post.likes.all %}
                            <a href="{% url 'YourArea:post_like' post.id %}"><span class="icon has-text-danger"><i class="fa-solid fa-heart"></i></span></a>
                        {% else %}
                            <a href="{% url 'YourArea:post_like' post.id %}"><span class="icon has-text-dark"><i class="fa-regular fa-heart"></i></span></a>
                        {% endif %}
                        <a href="{% url 'YourArea:likes' post.id %}">{{ post.number_of_likes }}</a>
                        <a href="{% url 'YourArea:post' post.id %}"><span class="icon has-text-dark"><i class="fa-regular fa-comment"></i></span></a>
                        {% if request.user.username == post.user.username %}
                            <a href="{% url 'YourArea:delete_post' post.id %}"><span class="icon has-text-dark"><i class="fa-solid fa-trash-can"></i></span></a>
                        {% endif %}
                    </p>
                    <span class="tag is-small has-text-grey-light">
                        {{ post.created_at }}
                    </span>
                    <hr>
                </div>
            </div>
        </a>
    </div>
{% endfor %}