YourArea/urls.py
from django.urls import path, include, re_path
from .views import *
import django.conf.urls

app_name = "YourArea"

urlpatterns = [
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    path("", dashboard, name="dashboard"),
    path("area_list/", profile_list, name="profile_list"),
    path("area/<int:pk>", profile, name="profile"),
    path("area/followers/<int:pk>", followers, name="followers"),
    path("area/following/<int:pk>", following, name="following"),
    path("post/<int:pk>", post, name="post"),
    path("post/<int:post_pk>/comment/<int:pk>/reply", CommentReplyView.as_view(), name="comment_reply"),
    path("post/likes/<int:pk>", likes, name="likes"),
    path("update_area/", update_area, name="update_area"),
    path("post_like/<int:pk>", post_like, name="post_like"),
    path("comment_like/<int:post_pk>/comment/<int:pk>/like", comment_like, name="comment_like"),
    path("delete_post/<int:pk>", delete_post, name="delete_post"),
    path("search/", search, name="search"),
    path('notification/<int:notification_pk>/post/<int:post_pk>', PostNotification.as_view(), name="post_notification"),
    path('notification/<int:notification_pk>/profile/<int:profile_pk>', FollowNotification.as_view(), name="follow_notification"),
    path('notification/delete/<int:notification_pk>', RemoveNotification.as_view(), name="notification_delete"),
    re_path(r"^register/", register, name="register"),
]

social/social/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('yourarea.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yourarea/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('@<str:username>', views.profile, name='area'),
    path('area/followers/<int:pk>/', views.followers, name='followers'),
    path('area/following/<int:pk>/', views.following, name='following'),
    path('update_area/', views.update_profile, name='update_area'),
    path('like-post/<int:post_id>/', views.like_post, name='like_post'),
    path('dislike-post/<int:post_id>/', views.dislike_post, name='dislike_post'),
    path('post/<int:pk>/', views.post, name='post'),
    path('delete-post/<int:pk>/', views.delete_post, name='delete_post'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications/mark-as-read/<int:notification_id>', views.mark_as_read, name='mark_as_read'),
    path("notifications/delete/<int:notification_id>/", views.delete_notification, name="delete_notification"),
    path('groups/', views.groups_list, name='groups_list'),
    path('group/create', views.create_group, name='create_group'),
    path('group/<slug:slug>', views.group, name='group'),
    path('group/<slug:slug>/join', views.join_group, name='join_group'),
    path('group/<slug:slug>/leave', views.leave_group, name='leave_group'),
    path('group/<slug:slug>/update', views.update_group, name='update_group'),
    path('group/<slug:slug>/create-event', views.create_event, name='create_event'),
    path('search/', views.search, name='search'),
    path('areas/', views.profiles_list, name='areas_list'),
]

YourArea/forms.py
from django import forms
from .models import Post, Comment, Profile
from django.contrib.auth.forms import UserCreationForm

class PostForm(forms.ModelForm):
    body = forms.CharField(
        required=False,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Post something...",
                "class": "textarea is-medium",
            }
        ),
        label="",
    )

    post_image = forms.ImageField(required=False)

    def clean(self):
        cleaned_data = super().clean()
        body = cleaned_data.get('body')
        post_image = cleaned_data.get('post_image')

        if not body and not post_image:
            raise forms.ValidationError(
                "You must fill in at least one of the fields."
            )

        return cleaned_data


    class Meta:
        model = Post
        exclude = ("user", "likes", )

class CommentForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Comment something...",
                "class": "textarea is-success is-medium",
            }
        ),
        label="",
    )
    

    class Meta:
        model = Comment
        exclude = ("user", "post", "likes", "parent")

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)

    def clean_username(self):
        username = self.cleaned_data.get('username')  # get the username data
        lowercase_username = username.lower()         # get the lowercase version of it

        return lowercase_username
        


class ProfileExtrasForm(forms.ModelForm):
    display_name = forms.CharField(label="Area name", widget=forms.widgets.Textarea(attrs={"class": "input"}))
    profile_image = forms.ImageField(label="Area picture")
    profile_bio = forms.CharField(label="Bio", required=False, widget=forms.widgets.Textarea(attrs={"placeholder": "Describe yourself...","class": "textarea",}))

    background_image = forms.ImageField(label="Background image", required=False)

    favourite_colour = forms.CharField(widget=forms.TextInput(attrs={"type": 'color'}))

    spotify_id = forms.CharField(label="Spotify song ID", required=False, widget=forms.TextInput(attrs={"class": "input"}))

    youtube_link = forms.CharField(label="YouTube", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    twitch_link = forms.CharField(label="Twitch", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    tiktok_link = forms.CharField(label="TikTok", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    instagram_link = forms.CharField(label="Instagram", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    custom_link = forms.CharField(label="Add site", required=False, widget=forms.TextInput(attrs={"class": "input"}))

    general_interests = forms.CharField(label="General interests", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    music_interests = forms.CharField(label="Music interests", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    television_interests = forms.CharField(label="Television interests", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    movies_interests = forms.CharField(label="Movies interests", required=False, widget=forms.TextInput(attrs={"class": "input"}))
    books_interests = forms.CharField(label="Books interests", required=False, widget=forms.TextInput(attrs={"class": "input"}))

    class Meta:
        model = Profile
        fields = ('display_name', 'profile_image', 'profile_bio', 'background_image', 'favourite_colour', 'spotify_id', 'youtube_link', 'twitch_link', 'tiktok_link', 'instagram_link', 'custom_link', 'general_interests', 'music_interests', 'television_interests', 'movies_interests', 'books_interests',)

YourArea/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from .models import *
from django.contrib.auth import login
from django.urls import reverse
from django.views import View
from django.http import HttpResponse

def dashboard(request):
    if request.user.is_authenticated:
        user_profile = Profile.objects.get(user__id=request.user.id)
        followed_posts = Post.objects.filter(user__id__in=request.user.profile.follows.all().values_list('user_id')).order_by("-created_at")
    else:
        followed_posts = None
    all_posts = Post.objects.all().order_by("-created_at")

    return render(
        request,
        "YourArea/dashboard.html",
        {"posts": all_posts, "followed_posts": followed_posts},
    )

def profile_list(request):
    profiles = Profile.objects.all().order_by("-date_modified")
    return render(request, "YourArea/profile_list.html", {"profiles": profiles})

def profile(request, pk):
    profile = Profile.objects.get(pk=pk)
    posts = profile.user.posts.all().order_by("-created_at")

    if request.user.is_authenticated:
        if not hasattr(request.user, 'profile'):
            missing_profile = profile(user=request.user)
            missing_profile.save()

        if request.method == "POST":
            current_user_profile = request.user.profile
            data = request.POST
            action = data.get("follow")
            if action == "follow":
                current_user_profile.follows.add(profile)
                notification = Notification.objects.create(notification_type=3, from_user=request.user, to_user=profile.user)
            elif action == "unfollow":
                current_user_profile.follows.remove(profile)
            current_user_profile.save()

            form = PostForm(request.POST or None, request.FILES or None)
            if form.is_valid():
                post = form.save(commit=False)
                post.user = request.user
                post.save()
                return redirect("YourArea:profile", current_user_profile.id)
        
    return render(request, "YourArea/profile.html", {"form": PostForm(), "profile": profile, "posts": posts})

def followers(request, pk):
    profiles = Profile.objects.get(user_id=pk)
    return render(request, "YourArea/followers.html", {"profiles": profiles})

def following(request, pk):
    profiles = Profile.objects.get(user_id=pk)
    return render(request, "YourArea/following.html", {"profiles": profiles})

def likes(request, pk):
    post = Post.objects.get(id=pk)
    users = post.likes.all()

    return render(request, "YourArea/likes.html", {"profiles": users})

def update_area(request):
    if request.user.is_authenticated:
        current_user = User.objects.get(id=request.user.id)
        profile_user = Profile.objects.get(user__id=request.user.id)

        # user_form = CustomUserCreationForm(request.POST or None, request.FILES or None, instance=current_user)
        profile_form = ProfileExtrasForm(request.POST or None, request.FILES or None, instance=profile_user, use_required_attribute=False)
        if profile_form.is_valid():
            # user_form.save()
            profile_form.save()
            # login(request, current_user)
            print("user changed")
            return redirect('YourArea:profile', current_user.profile.id)
        print("user not changed")
        return render(request, "YourArea/update_area.html", {'form': profile_form})
    else:
        return redirect('YourArea:dashboard')

def post(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST or None)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            notification = Notification.objects.create(notification_type=2, from_user=request.user, to_user=post.user, post=post)

    form = CommentForm()

    comments = Comment.objects.filter(post=post).order_by("-created_at")

    return render(
        request,
        "YourArea/post.html",
        {"form": form, "post": post, "comments": comments},
    )

class CommentReplyView(View):
    def post(self, request, post_pk, pk, *args, **kwargs):
        post = Post.objects.get(pk=post_pk)
        parent_comment = Comment.objects.get(pk=pk)
        form = CommentForm(request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post
            new_comment.parent = parent_comment
            new_comment.save()

        return redirect('YourArea:post', pk=post_pk)

def register(request):
    if request.method == "GET":
        return render(
            request, "YourArea/register.html",
            {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.backend = "django.contrib.auth.backends.ModelBackend"
            user.save()
            login(request, user)
            return redirect(reverse("YourArea:dashboard"))
        else:
            return render(
                request, "YourArea/register.html",
                {"form": CustomUserCreationForm}
            )

def post_like(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, id=pk)
        if post.likes.filter(id=request.user.id):
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)
            notification = Notification.objects.create(notification_type=1, from_user=request.user, to_user=post.user, post=post)
        return redirect(request.META.get("HTTP_REFERER"))

    else:
        return redirect('YourArea:login')

def comment_like(request, pk, *args, **kwargs):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, id=pk)
        if comment.likes.filter(id=request.user.id):
            comment.likes.remove(request.user)
        else:
            comment.likes.add(request.user)
            # notification = Notification.objects.create(notification_type=1, from_user=request.user, to_user=comment.user, post=post)
        return redirect(request.META.get("HTTP_REFERER"))

    else:
        return redirect('YourArea:login')

def delete_post(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, id=pk)
        if request.user.username == post.user.username:
            post.delete()
        return redirect(request.META.get("HTTP_REFERER"))

    else:
        return redirect(request.META.get("HTTP_REFERER"))

def search(request):
    if request.method == "POST":
        search = request.POST['search']

        searched = Post.objects.filter(body__contains = search).order_by("-created_at")
        searched_profiles = Profile.objects.filter(user__username__contains = search)

        return render(request, 'YourArea/search.html', {'search': search, 'searched': searched, 'searched_profiles': searched_profiles})
    else:
        return render(request, 'YourArea/search.html', {})

class PostNotification(View):
    def get(self, request, notification_pk, post_pk, *args, **kwargs):
        notification = Notification.objects.get(pk=notification_pk)
        post = Post.objects.get(pk=post_pk)

        notification.user_has_seen = True
        notification.save()

        return redirect('YourArea:post', pk=post_pk)

class FollowNotification(View):
    def get(self, request, notification_pk, profile_pk, *args, **kwargs):
        notification = Notification.objects.get(pk=notification_pk)
        profile = Profile.objects.get(pk=profile_pk)

        notification.user_has_seen = True
        notification.save()

        return redirect('YourArea:profile', pk=profile_pk)

class RemoveNotification(View):
    def delete(self, request, notification_pk, *args, **kwargs):
        notification = Notification.objects.get(pk=notification_pk)

        notification.user_has_seen = True
        notification.save()
        return HttpResponse('Success', content_type='text/plain')

YourArea/templates/YourArea/followers.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block content %}
<div class="column">
  <h1 class="title">Followers:</h1>

  {% show_area_list profiles.followed_by.all %}
</div>



{% endblock content %}

YourArea/templates/YourArea/following.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block content %}
<div class="column">
  <h1 class="title">Following:</h1>

  {% show_area_list profiles.follows.all %}
</div>

{% endblock content %}

YourArea/templates/YourArea/post.html
{% extends 'base.html' %}

{% block head %}
{% if post.post_image %}
    <meta property="og:image" content="http://ohio-reduce.gl.at.ply.gg:7832{{ post.post_image.url }}" />
{% endif %}
    <meta property="og:url" content="{% url 'YourArea:post' post.id %}" />
    <meta property="og:title" content="{{post.user.profile.display_name}} (@{{post.user.username}}) on YourArea" />
    <meta property="og:description" content="{{post.body}}" />
    <meta name="twitter:card" content="summary_large_image">
{% endblock %}

{% block content %}


<div class="container">
    <div class="box">
        <a href="{% url 'YourArea:profile' post.user.profile.id %}"><h1 class="title is-3">{{ post.user.username }}</h1></a>
        {{post.body}}
        <br>
        {% if post.post_image %}
            <img class="post-image" src="{{ post.post_image.url }}" alt="">
        {% endif %}
        <hr>
        <p>
            {% if user in post.likes.all %}
                <a href="{% url 'YourArea:post_like' post.id %}"><span class="icon has-text-danger"><i class="fa-solid fa-heart"></i></span></a>
            {% else %}
                <a href="{% url 'YourArea:post_like' post.id %}"><span class="icon has-text-dark"><i class="fa-regular fa-heart"></i></span></a>
            {% endif %}
            {{ post.number_of_likes }}
        </p>
        <span class="is-small has-text-grey-light">
            {{ post.created_at }}
        </span>
    </div>

    <h1 class="title is-2">Comments:</h1>
    <div class="block">
        <div class="block">
            <h2 class="title is-2">Add a Comment</p>
        </div>
        <div class="block">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button is-success is-fullwidth is-medium mt-5"
                        type="submit">Post
                </button>
            </form>
        </div>
    </div>

    {% for comment in comments %}
    {% if comment.is_parent %}
        <div class="block">
            <div class="media">
                <div class="media-left">
                    <p class="image is-48x48">
                        {% if comment.user.profile.profile_image %}
                            <img class="is-rounded" src="{{ comment.user.profile.profile_image.url }}">
                        {% else %}
                            <img class="is-rounded" src="https://bulma.io/assets/images/placeholders/128x128.png" />
                        {% endif %}
                    </p>
                    
                </div>
                <div class="media-content">
                    {% if comment.user.profile.display_name %}
                    <p class="mb-0"><strong class="has-text-dark">{{ comment.user.profile.display_name }}</strong> <small class="has-text-grey">@{{ comment.user.username }}</small></p>
                    {% else %}
                    <p class="mb-0"><strong class="has-text-dark">{{ comment.user.username }}</strong> <small class="has-text-grey">@{{ comment.user.username }}</small></p>
                    {% endif %}
                    <p class="is-text has-text-grey-dark">{{comment.body}}</p>
                    <p>
                        {% if user in comment.likes.all %}
                            <a href="{% url 'YourArea:comment_like' post.id comment.id %}"><span class="icon has-text-danger"><i class="fa-solid fa-heart"></i></span></a>
                        {% else %}
                            <a href="{% url 'YourArea:comment_like' post.id comment.id %}"><span class="icon has-text-dark"><i class="fa-regular fa-heart"></i></span></a>
                        {% endif %}
                        <a href="{% url 'YourArea:likes' comment.id %}">{{ comment.number_of_likes }}</a>
                        <a onclick="commentReplyToggle('{{ comment.id }}')"><span class="icon has-text-dark"><i class="fa-regular fa-comment"></i></span></a>
                    </p>
                    <span class="tag is-small has-text-grey-light">
                        {{ comment.created_at }}
                    </span>
                    <div class="block mt-5 is-hidden" id="{{ comment.id }}">
                        <form method="post" action="{% url 'YourArea:comment_reply' post.pk comment.pk %}">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="button is-success is-fullwidth is-medium mt-5"
                                    type="submit">Post
                            </button>
                        </form>
                        <hr>
                    </div>

                    {% for comment in comment.children %}
                        <div class="media">
                            <div class="media-left">
                                <p class="image is-48x48">
                                    {% if comment.user.profile.profile_image %}
                                        <img class="is-rounded" src="{{ comment.user.profile.profile_image.url }}">
                                    {% else %}
                                        <img class="is-rounded" src="https://bulma.io/assets/images/placeholders/128x128.png" />
                                    {% endif %}
                                </p>
                                
                            </div>
                            <div class="media-content">
                                {% if comment.user.profile.display_name %}
                                <p class="mb-0"><strong class="has-text-dark">{{ comment.user.profile.display_name }}</strong> <small class="has-text-grey">@{{ comment.user.username }}</small></p>
                                {% else %}
                                <p class="mb-0"><strong class="has-text-dark">{{ comment.user.username }}</strong> <small class="has-text-grey">@{{ comment.user.username }}</small></p>
                                {% endif %}
                                <p class="is-text has-text-grey-dark">{{comment.body}}</p>
                                <p>
                                    {% if user in comment.likes.all %}
                                        <a href="{% url 'YourArea:comment_like' post.id comment.id %}"><span class="icon has-text-danger"><i class="fa-solid fa-heart"></i></span></a>
                                    {% else %}
                                        <a href="{% url 'YourArea:comment_like' post.id comment.id %}"><span class="icon has-text-dark"><i class="fa-regular fa-heart"></i></span></a>
                                    {% endif %}
                                    <a href="{% url 'YourArea:likes' comment.id %}">{{ comment.number_of_likes }}</a>
                                    <a onclick="commentReplyToggle('{{ comment.id }}')"><span class="icon has-text-dark"><i class="fa-regular fa-comment"></i></span></a>
                                </p>
                                <span class="tag is-small has-text-grey-light">
                                    {{ comment.created_at }}
                                </span>
                                <div class="block mt-5 is-hidden" id="{{ comment.id }}">
                                    <form method="post" action="{% url 'YourArea:comment_reply' post.pk comment.parent.pk %}">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <button class="button is-success is-fullwidth is-medium mt-5"
                                                type="submit">Post
                                        </button>
                                    </form>
                                    <hr>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
    {% endfor %}
    
</div>

<script>
    function commentReplyToggle(parent_id) {
        const row = document.getElementById(parent_id);

        if (row.classList.contains('is-hidden')) {
            row.classList.remove('is-hidden');
        } else {
            row.classList.add('is-hidden');
        }
    }
</script>

{% endblock %}

YourArea/templates/YourArea/profile.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block head %}
<style>
    .container {
        /* margin: 0 25rem; */
        max-width: 900px;
        min-width: none;
    }


    .background {
        {% if profile.background_image %}
        background-image: url("{{profile.background_image.url}}");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover; /* Optional: ensures the image covers the entire background */
        background-position: center;
        {% endif %}
    }

    .column {
        background-color: white;
    }
</style>
{% endblock %}

{% block content %}



<div class="column profile">

    {% if profile.profile_image %}
        <img src="{{ profile.profile_image.url }}" alt="">
    {% endif %}
    <div class="block mb-0">
        <h1 class="title is-1 mb-0">
            {% if profile.display_name %}
            {{profile.display_name}}
            {% else %}
            {{profile.user.username}}
            {% endif %}
        </h1>
        <p class="is-4 has-text-grey">@{{profile.user.username}}</p>
        {% if profile.profile_bio %}
        {{profile.profile_bio}}
        <!-- <iframe id="output" sandbox="allow-scripts"></iframe> -->
        {% endif %}

        <script>
            const html = "{{profile.profile_bio}}";
            const output = document.getElementById('output');
            output.srcdoc = html;
        </script>
    </div>

    {% if profile.spotify_id %}
    <iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/{{profile.spotify_id}}?utm_source=generator" width="100%" height="100" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
    {% endif %}

    <div class="level">
        {% if profile.youtube_link %}
        <div class="level-item">
                <a href="{{ profile.youtube_link }}" target="new"><i class="fa-brands fa-youtube"></i></a>
        </div>
        {% endif %}
        {% if profile.twitch_link %}
        <div class="level-item">
                <a href="{{ profile.twitch_link }}" target="new"><i class="fa-brands fa-twitch"></i></a>
        </div>
        {% endif %}
        {% if profile.tiktok_link %}
        <div class="level-item">  
                <a href="{{ profile.tiktok_link }}" target="new"><i class="fa-brands fa-tiktok"></i></a>
        </div>
        {% endif %}
        {% if profile.instagram_link %}
        <div class="level-item">
                <a href="{{ profile.instagram_link }}" target="new"><i class="fa-brands fa-instagram"></i></a>
        </div>
        {% endif %}
        {% if profile.custom_link %}
        <div class="level-item">
                <a href="{{ profile.custom_link }}" target="new"><i class="fa-solid fa-link"></i></a>
        </div>
        {% endif %}
    </div>
    
    <div class="level">
        <div class="level-item"><a href="{% url 'YourArea:followers' profile.user.id %}"><p>{{profile.followed_by.all|length}} followers</p></a></div>
        <div class="level-item"><a href="{% url 'YourArea:following' profile.user.id %}"><p>{{profile.follows.all|length}} following</p></a></div>
        <div class="level-item"><p>{{profile.user.posts.all|length}} posts</p></div>
    </div>

    {% if request.user %}
        <form method="post">
            {% csrf_token %}
            <div class="columns">
            {% if profile in user.profile.follows.all %}
            <div class="column is-6">
                <button class="button is-danger" name="follow" value="unfollow">
                    Unfollow
                </button>
            </div>
            {% else %}
            <div class="column is-6">
                <button class="button is-success" name="follow" value="follow">
                    Follow
                </button>
            </div>
            {% endif %}
            {% if request.user.id == profile.user.id %}
            <div class="column is-6">
                <a class="button is-success is-centred" href="{% url 'YourArea:update_area' %}">Update profile</a>
            </div>
            {% endif %}
            </div>
        </form>
    {% endif %}
    
    <div class="box">
        <h1 class="title">{{profile.display_name}}'s interests</h1>
        <table class="table is-bordered is-fullwidth">
            <tbody>
                <tr>
                    <th>
                        <p>General</p>
                    </th>
                    <td>
                        {{ profile.general_interests }}
                    </td>
                </tr>
                <tr>
                    <th>
                        <p>Music</p>
                    </th>
                    <td>
                        {{ profile.music_interests }}
                    </td>
                </tr>
                <tr>
                    <th>
                        Television
                    </th>
                    <td>
                        {{ profile.television_interests }}
                    </td>
                </tr>
                <tr>
                    <th>
                        Movies
                    </th>
                    <td>
                        {{ profile.movies_interests }}
                    </td>
                </tr>
                <tr>
                    <th>
                        Books
                    </th>
                    <td>
                        {{ profile.books_interests }}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    
</div>

<div class="column is-8">
    <div class="content">
        {% if request.user.username == profile.user.username %}
        <a id="add-post" class="button mb-5">Add post</a>
        {% endif %}
        {% show_posts posts %}
    </div>

</div>

<div class="modal" id="post-modal">
    <div class="modal-background"></div>
    <div class="modal-content has-background-dark py-5 px-5">
        <div class="block">
            <div class="block">
                <h2 class="title is-2 has-text-light">Add a Post</p>
            </div>
            <div class="block">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="button is-success is-fullwidth is-medium mt-5"
                            type="submit">Post
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    const addPostButton = document.getElementById("add-post");
        const modalbg = document.querySelector('.modal-background');
        const modal = document.querySelector('.modal')

        addPostButton.addEventListener('click', () => {
            modal.classList.add('is-active');
        });

        modalbg.addEventListener('click', () => {
            modal.classList.remove('is-active');
        });
</script>

{% endblock content %}